/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.graforuta;

import DepJutiapa.ID;
import GrafosPkg.Grafo;

/**
 *
 * @author Usuario
 */
public class Municipios extends javax.swing.JFrame {

    /**
     * Creates new form Municipios
     */
     Grafo g = new Grafo("abcdefghijklmnopq");
     
    public Municipios() {
        g.agregarRuta('n','i', 23);
        g.agregarRuta('c','d', 20);
        g.agregarRuta('b','c',17);
        g.agregarRuta('c','e', 30);
        g.agregarRuta('c','o', 42);
        g.agregarRuta('h','c', 30);
        g.agregarRuta('n','g', 31);
        g.agregarRuta('m','q', 25);
        g.agregarRuta('p','l', 39);
        g.agregarRuta('e','j', 127);
        g.agregarRuta('a','h', 57);
        g.agregarRuta('k','a', 92);
        g.agregarRuta('q','e', 74);
        g.agregarRuta('m','n', 20);
        g.agregarRuta('d','q', 48);
        g.agregarRuta('b','f', 80);
        g.agregarRuta('i','g', 8);
        g.agregarRuta('d','l', 44);
        g.agregarRuta('e','f', 84);
        initComponents();
        
    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboInicio = new javax.swing.JComboBox<>();
        ComboFin = new javax.swing.JComboBox<>();
        LabRespuesta = new javax.swing.JLabel();
        ButtBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComboInicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua Blanca", "Santa Catarina Mita", "Asuncion Mita", "El Progreso", "Atescatempa", "Conguaco", "El Adelanto", "Zapotitlan", "Yupiltepeque", "Pasaco", "Moyuta", "San Jose Acatempa", "Quezada", "Jutiapa", "Jerez", "Comapa", "Jalpatagua" }));
        ComboInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboInicioActionPerformed(evt);
            }
        });

        ComboFin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua Blanca", "Santa Catarina Mita", "Asuncion Mita", "El Progreso", "Atescatempa", "Conguaco", "El Adelanto", "Zapotitlan", "Yupiltepeque", "Pasaco", "Moyuta", "San Jose Acatempa", "Quezada", "Jutiapa", "Jerez", "Comapa", "Jalpatagua" }));

        LabRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ButtBuscar.setText("Buscar Rutas");
        ButtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(ButtBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(ComboInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ComboFin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(LabRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboFin, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(ButtBuscar)
                .addGap(31, 31, 31)
                .addComponent(LabRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboInicioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ComboInicioActionPerformed

    private void ButtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtBuscarActionPerformed
        String InicioRuta;
        String FinRuta;
        InicioRuta = ComboInicio.getSelectedItem()+ "";
        FinRuta = ComboFin.getSelectedItem()+ "";
        ID e = new ID();
        char ir = e.MunisDepJut(InicioRuta);
        char fr = e.MunisDepJut(FinRuta);
        String respuesta = g.encontrarRutaMinimaDijkstra(ir, fr);
        LabRespuesta.setText(respuesta);
        
        
        
        
    }//GEN-LAST:event_ButtBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Municipios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Municipios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Municipios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Municipios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Municipios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtBuscar;
    private javax.swing.JComboBox<String> ComboFin;
    private javax.swing.JComboBox<String> ComboInicio;
    private javax.swing.JLabel LabRespuesta;
    // End of variables declaration//GEN-END:variables
}
